# -*- coding: utf-8 -*-
"""
DICIONÁRIO DE DADOS - TIC DOMICÍLIOS 2025
Este arquivo foi gerado automaticamente e contém o mapeamento de todas as variáveis.
"""

COLUNAS = {
    'QUEST': """Número de identificação do questionário""",
    'ID_DOMICILIO': """Número de identificação do domicílio""",
    'COD_UF': """UF (listagem  com código do IBGE)""",
    'AREA': """Área""",
    'RENDA_FAMILIAR': """Renda familiar""",
    'TV': """No domicílio tem televisor em cores? Quantos?""",
    'RADIO': """No domicílio tem rádio? Considere todos os rádios da casa, incluindo os rádios de aparelhos de som, de walkman. Não considerar rádio de automóveis. Quantos?""",
    'BANHEIRO': """No domicílio tem banheiros, incluindo todos os banheiros do domicílio, inclusive o de empregada? Quantos?""",
    'AUTOMOVEL': """No domicílio tem automóveis de passeio? Não considerar caminhões e veículos usados como taxi ou vans, kombis e caminhonetes utilizadas para uso profissional. Quantos?""",
    'EMPREGADA': """No domicílio tem empregada doméstica ou outros empregados da casa que trabalhem pelo menos 5 dias na semana. Quantos?""",
    'LAVA_ROUPA': """No domicílio tem máquina de lavar roupa do tipo que executa todo o processo de lavagem, desde o molho até a centrifugação. Não considerar o tipo "tanquinho". Quantos?""",
    'GELADEIRA': """No domicílio tem geladeira simples ou do tipo "duplex". Quantas?""",
    'FREEZER': """No domicílio tem freezer independente ou aquele que faz parte da geladeira, do tipo "duplex". Quantos?""",
    'LAVA_LOUCA': """No domicílio tem máquina lava-louças? Quantas?""",
    'DVD': """No domicílio tem DVD, incluindo outros aparelhos que reproduzem DVD, como videogames, computadores e notebooks, inclusive nos formatos mais modernos. Não considere DVD de carro? Quantos?""",
    'MICRO_ONDAS': """No domicílio tem microondas? Quantos?""",
    'MOTOCICLETA': """No domicílio tem motocicleta? Seja de uso exclusivo para passeio ou uso misto (trabalho e passeio). Não considerar somente trabalho. Quantas?""",
    'SECADORA': """No domicílio tem secadora de roupas? Quantas?""",
    'TELEFONE_FIXO': """No domicílio tem telefone fixo (não o aparelho, mas a linha telefônica)?""",
    'VIDEOGAME': """No domicílio tem aparelho de jogo ou vídeo game, Playstation, Nintendo Wii, Xbox?""",
    'TV_ASSINATURA': """No domicílio tem tv por assinatura (a Cabo, Satélite etc.)?""",
    'ANTENA_PARABOLICA': """No domicílio tem antena parabólica?""",
    'AGUA': """Tipo de abastecimento de água""",
    'RUA': """Tipo de pavimentação da rua""",
    'GRAU_INSTRUCAO': """Até que ano de escola o responsável pelo domicílio cursou?""",
    'PNADC_RD_A': """Nos últimos três meses, alguma pessoa desse domicílio recebeu rendimentos de Benefício Assistencial de Prestação Continuada ou BPC-LOAS?""",
    'PNADC_RD_B': """Nos últimos três meses, alguma pessoa desse domicílio recebeu rendimentos de Programa Bolsa Família ou Auxílio Brasil?""",
    'A1_A': """Neste domicílio tem Computador de mesa?""",
    'A1_B': """Neste domicílio tem notebook?""",
    'A1_C': """Neste domicílio tem Tablet?""",
    'A2_QTD_DESK': """Quantos computadores de mesa têm neste domicílio?""",
    'A2_QTD_NOTE': """Quantos notebooks têm neste domicílio?""",
    'A2_QTD_TAB': """Quantos tablets têm neste domicílio?""",
    'A4': """Este domicílio tem acesso à Internet?""",
    'A5_A': """O domicílio não tem acesso à Internet, por falta de computador no domicílio?""",
    'A5_B': """O domicílio não tem acesso à Internet, por falta de necessidade dos moradores?""",
    'A5_C': """O domicílio não tem acesso à Internet, por falta de interesse dos moradores?""",
    'A5_D': """O domicílio não tem acesso à Internet, porque os moradores têm acesso à Internet em outro lugar?""",
    'A5_E': """O domicílio não tem acesso à Internet, porque os moradores acham muito caro?""",
    'A5_F': """O domicílio não tem acesso à Internet, porque os moradores não sabem usar Internet?""",
    'A5_G': """O domicílio não tem acesso à Internet, por falta de disponibilidade de Internet na região do domicílio?""",
    'A5_H': """O domicílio não tem acesso à Internet, porque os moradores têm preocupações com segurança ou privacidade?""",
    'A5_I': """O domicílio não tem acesso à Internet, porque os moradores evitam o contato com conteúdo perigoso?""",
    'A5_OUTRO': """O domicílio não tem acesso à Internet, por outro motivo?""",
    'A5A': """E qual desses motivos é o principal?""",
    'A7A': """Neste domicílio tem Wi-Fi?""",
    'A7D': """Algum morador tem acesso à Internet no domicílio por meio de computador, tablet, telefone celular, televisão ou outro equipamento?""",
    'A7': """Qual o principal tipo de conexão utilizado para acessar a Internet no domicílio?""",
    'A7C': """Essa conexão via rede móvel 3G, 4G ou 5G é acessada por meio de""",
    'A7B': """A Internet utilizada neste domicilio é utilizada também em algum domicílio vizinho?""",
    'A8A': """Considerando as seguintes faixas, qual é a velocidade da Internet contratada neste domicílio?""",
    'A9A': """Qual o valor aproximadamente pago pela Internet contratada no domicílio?""",
    'A9B': """Esse valor refere-se a um pacote ou combo que inclui outros serviços, como telefone fixo ou canais de TV por assinatura, por exemplo?""",
    'A9C': """E o(a) sr(a) sabe o valor apenas da Internet?""",
    'A9D': """E qual o valor pago aproximadamente apenas pela Internet contratada neste domicílio?""",
    'PESO': """None""",
    'REP1': """None""",
    'REP2': """None""",
    'REP3': """None""",
    'REP4': """None""",
    'REP5': """None""",
    'REP6': """None""",
    'REP7': """None""",
    'REP8': """None""",
    'REP9': """None""",
    'REP10': """None""",
    'REP11': """None""",
    'REP12': """None""",
    'REP13': """None""",
    'REP14': """None""",
    'REP15': """None""",
    'REP16': """None""",
    'REP17': """None""",
    'REP18': """None""",
    'REP19': """None""",
    'REP20': """None""",
    'REP21': """None""",
    'REP22': """None""",
    'REP23': """None""",
    'REP24': """None""",
    'REP25': """None""",
    'REP26': """None""",
    'REP27': """None""",
    'REP28': """None""",
    'REP29': """None""",
    'REP30': """None""",
    'REP31': """None""",
    'REP32': """None""",
    'REP33': """None""",
    'REP34': """None""",
    'REP35': """None""",
    'REP36': """None""",
    'REP37': """None""",
    'REP38': """None""",
    'REP39': """None""",
    'REP40': """None""",
    'REP41': """None""",
    'REP42': """None""",
    'REP43': """None""",
    'REP44': """None""",
    'REP45': """None""",
    'REP46': """None""",
    'REP47': """None""",
    'REP48': """None""",
    'REP49': """None""",
    'REP50': """None""",
    'REP51': """None""",
    'REP52': """None""",
    'REP53': """None""",
    'REP54': """None""",
    'REP55': """None""",
    'REP56': """None""",
    'REP57': """None""",
    'REP58': """None""",
    'REP59': """None""",
    'REP60': """None""",
    'REP61': """None""",
    'REP62': """None""",
    'REP63': """None""",
    'REP64': """None""",
    'REP65': """None""",
    'REP66': """None""",
    'REP67': """None""",
    'REP68': """None""",
    'REP69': """None""",
    'REP70': """None""",
    'REP71': """None""",
    'REP72': """None""",
    'REP73': """None""",
    'REP74': """None""",
    'REP75': """None""",
    'REP76': """None""",
    'REP77': """None""",
    'REP78': """None""",
    'REP79': """None""",
    'REP80': """None""",
    'REP81': """None""",
    'REP82': """None""",
    'REP83': """None""",
    'REP84': """None""",
    'REP85': """None""",
    'REP86': """None""",
    'REP87': """None""",
    'REP88': """None""",
    'REP89': """None""",
    'REP90': """None""",
    'REP91': """None""",
    'REP92': """None""",
    'REP93': """None""",
    'REP94': """None""",
    'REP95': """None""",
    'REP96': """None""",
    'REP97': """None""",
    'REP98': """None""",
    'REP99': """None""",
    'REP100': """None""",
    'REP101': """None""",
    'REP102': """None""",
    'REP103': """None""",
    'REP104': """None""",
    'REP105': """None""",
    'REP106': """None""",
    'REP107': """None""",
    'REP108': """None""",
    'REP109': """None""",
    'REP110': """None""",
    'REP111': """None""",
    'REP112': """None""",
    'REP113': """None""",
    'REP114': """None""",
    'REP115': """None""",
    'REP116': """None""",
    'REP117': """None""",
    'REP118': """None""",
    'REP119': """None""",
    'REP120': """None""",
    'REP121': """None""",
    'REP122': """None""",
    'REP123': """None""",
    'REP124': """None""",
    'REP125': """None""",
    'REP126': """None""",
    'REP127': """None""",
    'REP128': """None""",
    'REP129': """None""",
    'REP130': """None""",
    'REP131': """None""",
    'REP132': """None""",
    'REP133': """None""",
    'REP134': """None""",
    'REP135': """None""",
    'REP136': """None""",
    'REP137': """None""",
    'REP138': """None""",
    'REP139': """None""",
    'REP140': """None""",
    'REP141': """None""",
    'REP142': """None""",
    'REP143': """None""",
    'REP144': """None""",
    'REP145': """None""",
    'REP146': """None""",
    'REP147': """None""",
    'REP148': """None""",
    'REP149': """None""",
    'REP150': """None""",
    'REP151': """None""",
    'REP152': """None""",
    'REP153': """None""",
    'REP154': """None""",
    'REP155': """None""",
    'REP156': """None""",
    'REP157': """None""",
    'REP158': """None""",
    'REP159': """None""",
    'REP160': """None""",
    'REP161': """None""",
    'REP162': """None""",
    'REP163': """None""",
    'REP164': """None""",
    'REP165': """None""",
    'REP166': """None""",
    'REP167': """None""",
    'REP168': """None""",
    'REP169': """None""",
    'REP170': """None""",
    'REP171': """None""",
    'REP172': """None""",
    'REP173': """None""",
    'REP174': """None""",
    'REP175': """None""",
    'REP176': """None""",
    'REP177': """None""",
    'REP178': """None""",
    'REP179': """None""",
    'REP180': """None""",
    'REP181': """None""",
    'REP182': """None""",
    'REP183': """None""",
    'REP184': """None""",
    'REP185': """None""",
    'REP186': """None""",
    'REP187': """None""",
    'REP188': """None""",
    'REP189': """None""",
    'REP190': """None""",
    'REP191': """None""",
    'REP192': """None""",
    'REP193': """None""",
    'REP194': """None""",
    'REP195': """None""",
    'REP196': """None""",
    'REP197': """None""",
    'REP198': """None""",
    'REP199': """None""",
    'REP200': """None""",
    'COD_REGIAO_2': """Região""",
    'RENDA_FAMILIAR_2': """Renda familiar""",
    'CLASSE_2015': """Classe social""",
    'A1_AGREG': """Domicílios com computador""",
    'DIC_CEL': """Domicílios que possuem equipamentos TIC""",
    'A1_EXCLUSIVOS': """Domicílios com computador, por tipo de computador presente de forma exclusiva ou simultânea no domicílio""",
    'A2_A_FAIXA': """Faixa de quantidade - Computador de mesa""",
    'A2_B_FAIXA': """Faixa de quantidade - Notebook""",
    'A2_C_FAIXA': """Faixa de quantidade - Tablet""",
    'A4_COB': """Domicilio com acesso a internet - ampliado""",
    'A1A4': """Domicílios por presença de computador e Internet""",
    'A7_AGREG': """Domicílios com acesso à Internet, por tipo de conexão""",
    'A5_NENHUM': """Domicílios sem acesso à Internet, por motivos para a falta de Internet""",
    'A9_FAIXA': """Domicílios com acesso à Internet, por valor pago pela principal conexão""",
    'TIPO_RM_NUM': """None""",
}

VALORES = {
    'COD_UF': {
        11.0: "RONDÔNIA",
        12.0: "ACRE",
        13.0: "AMAZONAS",
        14.0: "RORAIMA",
        15.0: "PARÁ",
        16.0: "AMAPÁ",
        17.0: "TOCANTINS",
        21.0: "MARANHÃO",
        22.0: "PIAUÍ",
        23.0: "CEARÁ",
        24.0: "RIO GRANDE DO NORTE",
        25.0: "PARAÍBA",
        26.0: "PERNAMBUCO",
        27.0: "ALAGOAS",
        28.0: "SERGIPE",
        29.0: "BAHIA",
        31.0: "MINAS GERAIS",
        32.0: "ESPIRITO SANTO",
        33.0: "RIO DE JANEIRO",
        35.0: "SÃO PAULO",
        41.0: "PARANÁ",
        42.0: "SANTA CATARINA",
        43.0: "RIO GRANDE DO SUL",
        50.0: "MATO GROSSO DO SUL",
        51.0: "MATO GROSSO",
        52.0: "GOIÁS",
        53.0: "DISTRITO FEDERAL",
    },
    'AREA': {
        1.0: "URBANA",
        2.0: "RURAL",
    },
    'RENDA_FAMILIAR': {
        1.0: "Até 1 SM",
        2.0: "Mais de 1 SM até 2 SM",
        3.0: "Mais de 2 SM até 3 SM",
        4.0: "Mais de 3 SM até 5 SM",
        5.0: "Mais de 5 SM até 10 SM",
        6.0: "Mais de 10 SM até 20 SM",
        7.0: "Mais de 20 SM até 30 SM",
        8.0: "Mais de 30 SM",
        9.0: "Não tem renda",
        97.0: "Não sabe",
        98.0: "Não respondeu",
    },
    'TV': {
        0.0: "Não tem",
        4.0: "4 ou mais",
    },
    'RADIO': {
        0.0: "Não tem",
        4.0: "4 ou mais",
    },
    'BANHEIRO': {
        0.0: "Não tem",
        4.0: "4 ou mais",
    },
    'AUTOMOVEL': {
        0.0: "Não tem",
        4.0: "4 ou mais",
    },
    'EMPREGADA': {
        0.0: "Não tem",
        4.0: "4 ou mais",
    },
    'LAVA_ROUPA': {
        0.0: "Não tem",
        4.0: "4 ou mais",
    },
    'GELADEIRA': {
        0.0: "Não tem",
        4.0: "4 ou mais",
    },
    'FREEZER': {
        0.0: "Não tem",
        4.0: "4 ou mais",
    },
    'LAVA_LOUCA': {
        0.0: "Não tem",
        4.0: "4 ou mais",
    },
    'DVD': {
        0.0: "Não tem",
        4.0: "4 ou mais",
    },
    'MICRO_ONDAS': {
        0.0: "Não tem",
        4.0: "4 ou mais",
    },
    'MOTOCICLETA': {
        0.0: "Não tem",
        4.0: "4 ou mais",
    },
    'SECADORA': {
        0.0: "Não tem",
        4.0: "4 ou mais",
    },
    'TELEFONE_FIXO': {
        0.0: "Não tem",
        1.0: "Tem",
    },
    'VIDEOGAME': {
        0.0: "Não tem",
        1.0: "Tem",
    },
    'TV_ASSINATURA': {
        0.0: "Não tem",
        1.0: "Tem",
    },
    'ANTENA_PARABOLICA': {
        0.0: "Não tem",
        1.0: "Tem",
    },
    'AGUA': {
        1.0: "Rede geral de distribuição",
        2.0: "Poço ou nascente",
        3.0: "Outro meio",
    },
    'RUA': {
        1.0: "Asfaltada/Pavimentada",
        2.0: "Terra/Cascalho",
    },
    'GRAU_INSTRUCAO': {
        1.0: "Analfabeto/ até 3ª Série Fundamental",
        2.0: "4ª a 7ª Série Fundamental",
        3.0: "Fundamental completo/ Médio incompleto",
        4.0: "Médio completo/ Superior incompleto",
        5.0: "Superior completo",
    },
    'PNADC_RD_A': {
        0.0: "Não",
        1.0: "Sim",
        97.0: "Não sabe",
        98.0: "Não respondeu",
    },
    'PNADC_RD_B': {
        0.0: "Não",
        1.0: "Sim",
        97.0: "Não sabe",
        98.0: "Não respondeu",
    },
    'A1_A': {
        0.0: "Não",
        1.0: "Sim",
        97.0: "Não sabe",
        98.0: "Não respondeu",
    },
    'A1_B': {
        0.0: "Não",
        1.0: "Sim",
        97.0: "Não sabe",
        98.0: "Não respondeu",
    },
    'A1_C': {
        0.0: "Não",
        1.0: "Sim",
        97.0: "Não sabe",
        98.0: "Não respondeu",
    },
    'A2_QTD_DESK': {
        1.0: "Um",
        2.0: "Dois",
        3.0: "Três",
        4.0: "Quatro",
        5.0: "Cinco",
        6.0: "Seis",
        7.0: "Sete",
        8.0: "Oito",
        999999999.0: "Não se aplica",
    },
    'A2_QTD_NOTE': {
        1.0: "Um",
        2.0: "Dois",
        3.0: "Três",
        4.0: "Quatro",
        5.0: "Cinco",
        6.0: "Seis",
        7.0: "Sete",
        8.0: "Oito",
        999999999.0: "Não se aplica",
    },
    'A2_QTD_TAB': {
        1.0: "Um",
        2.0: "Dois",
        3.0: "Três",
        4.0: "Quatro",
        5.0: "Cinco",
        6.0: "Seis",
        7.0: "Sete",
        8.0: "Oito",
        999999999.0: "Não se aplica",
    },
    'A4': {
        0.0: "Não",
        1.0: "Sim",
        97.0: "Não sabe",
        98.0: "Não respondeu",
    },
    'A5_A': {
        0.0: "Não",
        1.0: "Sim",
        97.0: "Não sabe",
        98.0: "Não respondeu",
        99.0: "Não se aplica",
    },
    'A5_B': {
        0.0: "Não",
        1.0: "Sim",
        97.0: "Não sabe",
        98.0: "Não respondeu",
        99.0: "Não se aplica",
    },
    'A5_C': {
        0.0: "Não",
        1.0: "Sim",
        97.0: "Não sabe",
        98.0: "Não respondeu",
        99.0: "Não se aplica",
    },
    'A5_D': {
        0.0: "Não",
        1.0: "Sim",
        97.0: "Não sabe",
        98.0: "Não respondeu",
        99.0: "Não se aplica",
    },
    'A5_E': {
        0.0: "Não",
        1.0: "Sim",
        97.0: "Não sabe",
        98.0: "Não respondeu",
        99.0: "Não se aplica",
    },
    'A5_F': {
        0.0: "Não",
        1.0: "Sim",
        97.0: "Não sabe",
        98.0: "Não respondeu",
        99.0: "Não se aplica",
    },
    'A5_G': {
        0.0: "Não",
        1.0: "Sim",
        97.0: "Não sabe",
        98.0: "Não respondeu",
        99.0: "Não se aplica",
    },
    'A5_H': {
        0.0: "Não",
        1.0: "Sim",
        97.0: "Não sabe",
        98.0: "Não respondeu",
        99.0: "Não se aplica",
    },
    'A5_I': {
        0.0: "Não",
        1.0: "Sim",
        97.0: "Não sabe",
        98.0: "Não respondeu",
        99.0: "Não se aplica",
    },
    'A5_OUTRO': {
        0.0: "Não",
        1.0: "Sim",
        99.0: "Não se aplica",
    },
    'A5A': {
        1.0: "Por falta de computador no domicílio",
        2.0: "Por falta de necessidade dos moradores",
        3.0: "Por falta de interesse dos moradores",
        4.0: "Porque os moradores têm acesso à Internet em outro lugar",
        5.0: "Porque os moradores acham muito caro",
        6.0: "Porque os moradores não sabem usar Internet",
        7.0: "Por falta de disponibilidade de Internet na região do domicílio",
        8.0: "Porque os moradores têm preocupações com segurança ou privacidade",
        9.0: "Porque os moradores evitam o contato com conteúdo perigoso",
        10.0: "Outro motivo",
        97.0: "Não sabe",
        98.0: "Não respondeu",
        99.0: "Não se aplica",
    },
    'A7A': {
        0.0: "Não",
        1.0: "Sim",
        97.0: "Não sabe",
        98.0: "Não respondeu",
        99.0: "Não se aplica",
    },
    'A7D': {
        0.0: "Não",
        1.0: "Sim",
        97.0: "Não sabe",
        98.0: "Não respondeu",
        99.0: "Não se aplica",
    },
    'A7': {
        1.0: "Conexão discada, que deixa a linha de telefone ocupada durante o uso",
        2.0: "Conexão DSL, via linha telefônica, que não deixa a linha ocupada durante o uso",
        3.0: "Conexão via cabo de TV ou fibra ótica",
        4.0: "Conexão via sinal de Rádio",
        5.0: "Conexão via sinal de Satélite",
        6.0: "Conexão móvel via modem ou chip 3G ou 4G",
        97.0: "Não sabe",
        98.0: "Não respondeu",
        99.0: "Não se aplica",
    },
    'A7C': {
        1.0: "Um telefone celular",
        2.0: "Um modem USB conectado diretamente no computador ou um aparelho modem ligado na tomada",
        3.0: "Outro equipamento",
        97.0: "Não sabe",
        98.0: "Não respondeu",
        99.0: "Não se aplica",
    },
    'A7B': {
        0.0: "Não",
        1.0: "Sim",
        97.0: "Não sabe",
        98.0: "Não respondeu",
        99.0: "Não se aplica",
    },
    'A8A': {
        1.0: "Até 4 megas por segundo",
        2.0: "De 5 a 10 megas por segundo",
        3.0: "De 11 a 50 megas por segundo",
        4.0: "De 51 a 100 megas por segundo",
        5.0: "De 101 a 300 megas por segundo",
        6.0: "De 301 a 500 megas por segundo",
        7.0: "501 megas por segundo ou mais",
        97.0: "Não sabe",
        98.0: "Não respondeu",
        99.0: "Não se aplica",
    },
    'A9A': {
        0.0: "Não paga nada",
        1.0: "Até R$ 10",
        2.0: "De R$11 a R$ 20",
        3.0: "De R$21 a R$ 30",
        4.0: "De R$31 a R$ 40",
        5.0: "De R$41 a R$ 50",
        6.0: "De R$51 a R$ 60",
        7.0: "De R$61 a R$ 70",
        8.0: "De R$71 a R$ 80",
        9.0: "De R$81 a R$ 90",
        10.0: "De R$91 a R$ 100",
        11.0: "De R$101 a R$ 110",
        12.0: "De R$111 a R$ 120",
        13.0: "De R$121 a R$ 130",
        14.0: "De R$131 a R$ 140",
        15.0: "De R$141 a R$ 150",
        16.0: "Acima de R$ 150",
        17.0: "Não paga nada",
        97.0: "Não sabe",
        98.0: "Não respondeu",
        99.0: "Não se aplica",
    },
    'A9B': {
        0.0: "Não",
        1.0: "Sim",
        97.0: "Não sabe",
        98.0: "Não respondeu",
        99.0: "Não se aplica",
    },
    'A9C': {
        0.0: "Não",
        1.0: "Sim",
        99.0: "Não se aplica",
    },
    'A9D': {
        0.0: "Não paga nada",
        1.0: "Até R$ 10",
        2.0: "De R$11 a R$ 20",
        3.0: "De R$21 a R$ 30",
        4.0: "De R$31 a R$ 40",
        5.0: "De R$41 a R$ 50",
        6.0: "De R$51 a R$ 60",
        7.0: "De R$61 a R$ 70",
        8.0: "De R$71 a R$ 80",
        9.0: "De R$81 a R$ 90",
        10.0: "De R$91 a R$ 100",
        11.0: "De R$101 a R$ 110",
        12.0: "De R$111 a R$ 120",
        13.0: "De R$121 a R$ 130",
        14.0: "De R$131 a R$ 140",
        15.0: "De R$141 a R$ 150",
        16.0: "Acima de R$ 150",
        17.0: "Não paga nada",
        97.0: "Não sabe",
        98.0: "Não respondeu",
        99.0: "Não se aplica",
    },
    'COD_REGIAO_2': {
        1.0: "Sudeste",
        2.0: "Nordeste",
        3.0: "Sul",
        4.0: "Norte",
        5.0: "Centro-Oeste",
    },
    'RENDA_FAMILIAR_2': {
        1.0: "Até 1 SM",
        2.0: "Mais de 1 SM até 2 SM",
        3.0: "Mais de 2 SM até 3 SM",
        4.0: "Mais de 3 SM até 5 SM",
        5.0: "Mais de 5 SM até 10 SM",
        6.0: "Mais de 10 SM",
        7.0: "Não tem renda",
        97.0: "Não sabe",
        98.0: "Não respondeu",
    },
    'CLASSE_2015': {
        1.0: "A",
        2.0: "B",
        3.0: "C",
        4.0: "DE",
    },
    'A1_AGREG': {
        1.0: "Sim",
        0.0: "Não",
    },
    'DIC_CEL': {
        1.0: "Telefone celular",
    },
    'A1_EXCLUSIVOS': {
        1.0: "Apenas computador de mesa",
        2.0: "Apenas notebook",
        3.0: "Apenas tablet",
        99.0: "Mais de um tipo de computador",
    },
    'A2_A_FAIXA': {
        0.0: "Nenhum",
        1.0: "Um",
        2.0: "Dois ou mais",
    },
    'A2_B_FAIXA': {
        0.0: "Nenhum",
        1.0: "Um",
        2.0: "Dois ou mais",
    },
    'A2_C_FAIXA': {
        0.0: "Nenhum",
        1.0: "Um",
        2.0: "Dois ou mais",
    },
    'A4_COB': {
        1.0: "Sim",
        0.0: "Não",
    },
    'A1A4': {
        1.0: "Ambos",
        2.0: "Apenas computador",
        3.0: "Apenas Internet",
        4.0: "Nem computador nem Internet",
    },
    'A7_AGREG': {
        1.0: "Total - Banda larga fixa",
    },
    'A5_NENHUM': {
        1.0: "Nenhum desses motivos",
    },
    'A9_FAIXA': {
        1.0: "Até R$ 30",
        2.0: "R$ 31 a R$ 40",
        3.0: "R$ 41 a R$ 50",
        4.0: "R$ 51 a R$ 60",
        5.0: "R$ 61 a R$ 70",
        6.0: "R$ 71 a R$ 80",
        7.0: "R$ 81 a R$ 90",
        8.0: "R$ 91 a R$ 100",
        9.0: "R$ 101 a R$ 150",
        10.0: "Mais de R$ 150",
        97.0: "Não sabe",
        98.0: "Não respondeu",
    },
}

def buscar(termo):
    """Função utilitária para buscar colunas por termo ou descrição."""
    termo = termo.upper()
    resultados = []
    for col, desc in COLUNAS.items():
        if termo in col or (desc and termo in desc.upper()):
            resultados.append((col, desc))
    return resultados
