CATEGORIAS_DOMICILIO = {
    "📊 Acesso e Conectividade": {
        'A4': 'Acesso à Internet',
        'A4_COB': 'Acesso à Internet (ampliado)',
        'A7D': 'Algum morador tem acesso à Internet',
        'A1A4': 'Presença de computador e Internet',
    },
    "💻 Equipamentos - Disponibilidade": {
        'A1_A': 'Possui Computador de mesa',
        'A1_B': 'Possui Notebook',
        'A1_C': 'Possui Tablet',
        'A1_AGREG': 'Possui algum tipo de computador',
        'A1_EXCLUSIVOS': 'Tipo de computador (exclusivo/simultâneo)',
        'DIC_CEL': 'Equipamentos TIC no domicílio',
        'EQUIPAMENTOS_COMPUTADOR': ['A1_A', 'A1_B', 'A1_C'],
    },
    "🔢 Equipamentos - Quantidade": {
        'A2_QTD_DESK': 'Quantidade de computadores de mesa',
        'A2_QTD_NOTE': 'Quantidade de notebooks',
        'A2_QTD_TAB': 'Quantidade de tablets',
        'A2_A_FAIXA': 'Faixa de quantidade - Computador de mesa',
        'A2_B_FAIXA': 'Faixa de quantidade - Notebook',
        'A2_C_FAIXA': 'Faixa de quantidade - Tablet',
    },
    "🌐 Tipo de Conexão": {
        'A7': 'Principal tipo de conexão',
        'A7A': 'Possui WiFi',
        'A7B': 'Internet compartilhada com vizinho',
        'A7C': 'Meio de acesso à rede móvel (3G/4G/5G)',
        'A7_AGREG': 'Tipo de conexão (agregado)',
    },
    "⚡ Velocidade e Custo": {
        'A8A': 'Velocidade da Internet contratada',
        'A9A': 'Valor pago pela Internet',
        'A9B': 'Valor inclui pacote/combo',
        'A9C': 'Sabe o valor apenas da Internet',
        'A9D': 'Valor pago apenas pela Internet',
        'A9_FAIXA': 'Faixa de valor pago pela conexão',
    },
    "🚫 Barreiras - Individual": {
        'A5_A': 'Falta de computador',
        'A5_B': 'Falta de necessidade',
        'A5_C': 'Falta de interesse',
        'A5_D': 'Acesso em outro lugar',
        'A5_E': 'Muito caro',
        'A5_F': 'Não sabem usar',
        'A5_G': 'Falta de disponibilidade na região',
        'A5_H': 'Preocupações com segurança/privacidade',
        'A5_I': 'Evitam conteúdo perigoso',
        'A5_OUTRO': 'Outro motivo',
    },
    "🎯 Barreiras - Análise": {
        'A5A': 'Principal motivo de falta de Internet',
        'A5_NENHUM': 'Motivos para falta de Internet',
        'BARREIRAS_PRINCIPAIS': ['A5_A', 'A5_B', 'A5_C', 'A5_E', 'A5_F'],
        'BARREIRAS_TODAS': ['A5_A', 'A5_B', 'A5_C', 'A5_D', 'A5_E', 'A5_F', 'A5_G', 'A5_H', 'A5_I'],
    },
    "🏠 Características do Domicílio": {
        'TV_ASSINATURA': 'Possui TV por assinatura',
        'ANTENA_PARABOLICA': 'Possui antena parabólica',
        'RUA': 'Tipo de pavimentação da rua',
    },
    "👥 Perfil Socioeconômico": {
        'RENDA_FAMILIAR': 'Renda familiar',
        'RENDA_FAMILIAR_2': 'Renda familiar (v2)',
        'CLASSE_2015': 'Classe social',
        'GRAU_INSTRUCAO': 'Escolaridade do responsável',
        'PNADC_RD_A': 'Recebe BPC-LOAS',
        'PNADC_RD_B': 'Recebe Bolsa Família/Auxílio Brasil',
    },
    "📍 Localização": {
        'COD_UF': 'UF',
        'COD_REGIAO_2': 'Região',
        'AREA': 'Área (Urbana/Rural)',
    },
}

CATEGORIAS_INDIVIDUOS = {
    "🌐 Acesso e Uso Básico": {
        'C1': 'Já usou a Internet?',
        'C3': 'Última vez que usou Internet',
        'C3J3': 'Usuário de internet (ampliado)',
        'C4': 'Frequência de uso da Internet',
        'C1_COB_A': 'Já enviou/recebeu e-mails?',
        'C1_COB_B': 'Já mandou mensagens por WhatsApp/Telegram?',
        'C1_COB_C1': 'Já usou redes sociais (Facebook/TikTok)?',
        'C1_COB_D': 'Já buscou informações (Google/Bing)?',
    },
    "🚫 Barreiras de Acesso": {
        'C2_D': 'Não tem onde acessar',
        'C2_E': 'Muito caro',
        'C2_F': 'Preocupações com segurança/privacidade',
        'C2_G': 'Evitar conteúdo perigoso',
        'C2_I': 'Falta de interesse/necessidade',
        'C2_J': 'Não sabe usar',
        'C2_OUTRO': 'Outro motivo',
        'C2A': 'Principal motivo para não usar',
    },
    "💻 Dispositivos Utilizados": {
        'C5_A': 'Computador de mesa',
        'C5_B': 'Notebook',
        'C5_C': 'Tablet',
        'C5_D': 'Telefone celular',
        'C5_E': 'Videogame',
        'C5_F': 'Televisão',
        'C5_OUTRO': 'Outro aparelho',
        'C5_DISPOSITIVOS': 'Celular e computador (exclusivo/simultâneo)',
        'DISPOSITIVOS_TODOS': ['C5_A', 'C5_B', 'C5_C', 'C5_D', 'C5_E', 'C5_F'],
    },
    "📍 Locais de Acesso": {
        'C6_A': 'Em casa',
        'C6_B': 'No trabalho',
        'C6_C': 'Na escola/ensino',
        'C6_D': 'Casa de outra pessoa',
        'C6_E': 'Centro público gratuito',
        'C6_F': 'Centro público pago (lanhouse)',
        'C6_G': 'Deslocando-se (rua/ônibus/metrô)',
        'C6A': 'Local mais frequente',
        'LOCAIS_TODOS': ['C6_A', 'C6_B', 'C6_C', 'C6_D', 'C6_E', 'C6_F', 'C6_G'],
    },
    "💬 Comunicação": {
        'C7_A': 'E-mail',
        'C7_B': 'Mensagens instantâneas (WhatsApp/Skype)',
        'C7_C': 'Voz/vídeo (Skype/WhatsApp)',
        'C7_D1': 'Redes sociais (Facebook/Instagram/TikTok)',
        'C7_E': 'Listas de discussão/fóruns',
        'C7_F': 'Microblog (X/Twitter)',
    },
    "🔍 Busca de Informações": {
        'C8_A': 'Produtos e serviços',
        'C8_B': 'Saúde',
        'C8_C': 'Viagens e acomodações',
        'C8_D': 'Emprego/enviar currículos',
        'C8_E': 'Wikipédia',
        'C8_F': 'Sites de governo',
        'C8_G': 'Serviços públicos online',
        'C8_H': 'Transações financeiras',
        'C8_I': 'Pagamento/transferência Pix',
    },
    "🎬 Entretenimento": {
        'C9_A': 'Jogos online',
        'C9_B': 'Ouvir música (Spotify/Deezer/YouTube)',
        'C9_C': 'Vídeos/filmes/séries (YouTube/Netflix)',
        'C9_D': 'Jornais/revistas/notícias',
        'C9_E': 'Transmissões ao vivo/lives',
        'C9_F': 'Exposições e museus',
        'C9_G': 'Podcasts',
    },
    "📚 Educação e Trabalho": {
        'C10_A': 'Atividades/pesquisas escolares',
        'C10_B': 'Cursos à distância',
        'C10_C': 'Informações sobre cursos superiores',
        'C10_D': 'Estudar por conta própria',
        'C10_E': 'Armazenamento na nuvem (Dropbox/Drive)',
        'C10_F': 'Atividades de trabalho',
    },
    "🎨 Criação de Conteúdo": {
        'C11_A': 'Compartilhar conteúdo (textos/imagens/vídeos)',
        'C11_B': 'Criar/atualizar blogs/websites',
        'C11_C': 'Postar conteúdo próprio',
        'TC10_A': 'Postou textos que criou',
        'TC10_B': 'Postou imagens/fotos que criou',
        'TC10_C': 'Postou vídeos que criou',
        'TC10_D': 'Postou músicas que criou',
    },
    "🤖 Inteligência Artificial": {
        'C13A': 'Usou IA (ChatGPT/Copilot/Gemini)',
        'C13B_A': 'IA para trabalho profissional',
        'C13B_B': 'IA para pesquisa escolar',
        'C13B_C': 'IA para uso pessoal',
        'C13C_A': 'Não usou: falta de interesse',
        'C13C_B': 'Não usou: não conhecia',
        'C13C_C': 'Não usou: falta de habilidade',
        'C13C_D': 'Não usou: preocupações segurança',
    },
    "🎰 Apostas Online": {
        'C14_A': 'Loteria federal (Mega Sena/Lotofácil)',
        'C14_B': 'Cassino online (jogo do tigrinho)',
        'C14_C': 'Apostas esportivas (Bet365/Betano)',
        'C14_D': 'Rifas digitais/sorteios',
    },
    "🏛️ Governo Eletrônico": {
        'G1_A': 'Documentos pessoais (RG/CPF)',
        'G1_B': 'Saúde pública',
        'G1_C': 'Educação pública (ENEM/PROUNI)',
        'G1_D': 'INSS/FGTS/previdência',
        'G1_E': 'Impostos (IR/IPVA/IPTU)',
        'G1_F': 'Polícia e segurança',
        'G1_G': 'Transporte público',
        'G1_H': 'Justiça (processos/defensoria)',
        'G5_A': 'Acessou Gov.br para si',
        'G5_B': 'Acessou Gov.br para outra pessoa',
    },
    "🛒 Comércio Eletrônico": {
        'H2': 'Comprou/encomendou produtos online (12 meses)',
    },
    "💡 Habilidades Digitais": {
        'I1A_A': 'Copiar/mover arquivos',
        'I1A_B': 'Copiar e colar conteúdo',
        'I1A_C': 'Anexar documentos/imagens',
        'I1A_D': 'Usar fórmulas em planilhas',
        'I1A_E': 'Conectar/instalar equipamentos',
        'I1A_F': 'Instalar programas/aplicativos',
        'I1A_G': 'Transferir arquivos entre dispositivos',
        'I1A_H': 'Escrever programas de software',
    },
    "🔒 Segurança e Privacidade": {
        'I2_A': 'Verificar se o site é seguro',
        'I2_B': 'Configurar privacidade em redes sociais',
        'I2_C': 'Negar acesso a localização',
        'I2_D': 'Recusou cookies',
        'I2_E': 'Mudou senhas',
        'I2_F': 'Usou conexões seguras/VPN',
    },
    "📱 Telefone Celular": {
        'J1': 'Possui telefone celular',
        'J2': 'Tipo de celular (smartphone/convencional)',
        'J3_A': 'Internet por WiFi',
        'J3_B': 'Internet móvel (3G/4G/5G)',
        'J4': 'Uso exclusivo ou compartilhado',
        'J5': 'É o dono do celular',
    },
    "👤 Perfil Demográfico": {
        'SEXO': 'Sexo',
        'IDADE': 'Idade',
        'FAIXA_ETARIA': 'Faixa etária',
        'GRAU_INSTRUCAO_1': 'Grau de instrução',
        'ESTUD': 'Frequenta escola/universidade',
        'RACA': 'Raça/cor',
    },
    "💼 Situação Profissional": {
        'TRAB': 'Trabalhou na última semana',
        'OCUP_CLASS': 'Classificação ocupacional',
        'PNADC_REMU_FORMAL': 'Recebe remuneração formal',
    },
    "📍 Localização Individual": {
        'COD_UF': 'UF',
        'COD_REGIAO_2': 'Região',
        'AREA': 'Área (Urbana/Rural)',
        'RENDA_FAMILIAR': 'Renda familiar',
        'CLASSE_2015': 'Classe social',
    },
}
